language: ruby

addons:
  code_climate:
    repo_token: 17abb3979e6abb0cee4069ec3e7aeee9c6e4fd8277b0899b4cd0900ac6030f98

rvm:
  - '2.0'
  - '2.1'
  - '2.2'
  - '2.3'
  - rbx-2.5.1
  - jruby

# Part of test suite - building gem and trying to require it via ruby -e
# This way we check if gem is loadable and works without any problems in vanilla ruby
script: >
  rake build&&gem install pkg/tsv*.gem&&ruby -e 'require "tsv"; TSV.parse_file("spec/fixtures/example.tsv").to_a'&&rake

matrix:
  allow_failures:
    - rvm: rbx-2.5.1
    - rvm: jruby
